use cpp_inherit::*;
include!("test.rs"); // autogenerated by bindgen

#[inherit_from(BaseType)]
#[derive(Debug)]
struct RustType {}

#[inherit_from_impl(BaseType, "test.hpp")]
impl RustType {
    fn new() -> Self {
        Self {
            _base: BaseType { vtable_: RustType::VTABLE_ as _, value: 3 }
        }
    }

    #[overridden] fn x(&self) -> i32 {
        99
    }
}

fn main() {
    let mut test = RustType::new();
    dbg!(test.value);
    dbg!(test.x());

    unsafe {
        let test: &mut BaseType = &mut test;
        dbg!(call_x_on(test));
    }
}
